services:
  frontend:
    image: ghcr.io/zinackes/robux_republic_front/frontendbank:latest
    container_name: react_app
    restart: always
    ports:
      - "6683:3000"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - reseau_partage

networks:
  reseau_partage:
    external: true
    name: global_network